name: ideen
description: "簡単・安全にIDをシェア＆マッチング"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase関連
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  
  # 状態管理
  provider: ^6.1.2
  
  # UI/UX
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
  # ユーティリティ
  intl: ^0.20.2  # flutter_localizationsの要求に合わせる
  uuid: ^4.5.1
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.3
  
  # フォーム・バリデーション
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.0.0
  
  # その他
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  http: ^1.2.2

  # アイコン
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # アセット設定（後で追加）
  # assets:
  #   - assets/images/
  #   - assets/icons/