// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdQULMIaerR3t7egrISQnNNq_0F8s18DI',
    appId: '1:101958089793:web:ef5deb5bc69b82b74c5ac0',
    messagingSenderId: '101958089793',
    projectId: 'ideen-b0525',
    authDomain: 'ideen-b0525.firebaseapp.com',
    storageBucket: 'ideen-b0525.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdwBHjAX62zZhf5vWf4Mhxeds859IsGn4',
    appId: '1:101958089793:android:ff7fdf68627a97b24c5ac0',
    messagingSenderId: '101958089793',
    projectId: 'ideen-b0525',
    storageBucket: 'ideen-b0525.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQKvPcsmkYtjw5_00iCG8146XrtvCYTOI',
    appId: '1:101958089793:ios:e98b5257b7677e764c5ac0',
    messagingSenderId: '101958089793',
    projectId: 'ideen-b0525',
    storageBucket: 'ideen-b0525.firebasestorage.app',
    iosBundleId: 'com.ideen.app.ideen',
  );
}
